-- RayTrace filesystem syscall catalog, version 1.
-- Classification reference only: loading this file does NOT enable tracing.
-- Standalone SQLite database; do not add to application migrations.
-- Names are Linux syscall names, not shell commands, libc aliases or syscall numbers.
-- Re-import updates catalog-owned seed rows without replacing/deleting other rows.
-- Event outcome and confirmed effect must remain separate from default impact.
PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS syscall_impact_levels (
    level INTEGER PRIMARY KEY CHECK (level BETWEEN 0 AND 3),
    label TEXT NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS syscall_categories (
    category_id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS syscall_catalog (
    syscall_name TEXT PRIMARY KEY,
    description TEXT NOT NULL CHECK (length(trim(description)) > 0),
    category_id TEXT NOT NULL REFERENCES syscall_categories(category_id),
    default_impact_level INTEGER REFERENCES syscall_impact_levels(level)
        CHECK (default_impact_level IS NULL OR default_impact_level BETWEEN 0 AND 3),
    classification_rule TEXT NOT NULL CHECK (length(trim(classification_rule)) > 0),
    required_evidence TEXT NOT NULL CHECK (length(trim(required_evidence)) > 0),
    interpretation_notes TEXT NOT NULL CHECK (length(trim(interpretation_notes)) > 0),
    catalog_version INTEGER NOT NULL DEFAULT 1 CHECK (catalog_version = 1)
);

INSERT INTO syscall_impact_levels (level, label, description) VALUES
(0, 'Observe', 'Read or inspect without an explicit mutation request; sensitive reads and incidental atime updates are possible. Impact is not maliciousness.'),
(1, 'Create', 'Add a filesystem entry without replacing existing data. Impact is not maliciousness.'),
(2, 'Modify', 'Change existing file contents, metadata, layout or location. Impact is not maliciousness.'),
(3, 'Remove/replace', 'Remove a filesystem entry or replace an existing destination. Impact is not maliciousness.')
ON CONFLICT(level) DO UPDATE SET label=excluded.label, description=excluded.description;

INSERT INTO syscall_categories (category_id, label, description) VALUES
('open', 'Open', 'Open a file with access and optional creation or truncation semantics.'),
('read', 'Read', 'Read file data.'),
('inspect', 'Inspect', 'Inspect metadata, directory entries or link targets.'),
('create_directory', 'Create directory', 'Add a directory.'),
('write', 'Write', 'Write or append file data.'),
('resize', 'Resize / allocate', 'Set file length or manipulate file ranges.'),
('delete', 'Delete', 'Remove a filesystem entry.'),
('rename', 'Rename / replace', 'Move, exchange or replace filesystem entries.'),
('copy', 'Copy / transfer', 'Transfer data between descriptors.'),
('metadata_change', 'Metadata change', 'Change file permissions, ownership, attributes or timestamps.'),
('link', 'Create link', 'Add a hard link or symbolic link.'),
('mapping', 'Memory mapping', 'Establish or manage potentially file-backed memory mappings.'),
('descriptor_bookkeeping', 'Descriptor / path bookkeeping', 'Track descriptor state, path context or synchronization.')
ON CONFLICT(category_id) DO UPDATE SET label=excluded.label, description=excluded.description;

INSERT INTO syscall_catalog
    (syscall_name, description, category_id, default_impact_level,
     classification_rule, required_evidence, interpretation_notes)
VALUES
('open', 'Opens a pathname and may create or truncate a file.', 'open', NULL, 'open_effect', 'path, dirfd/base path, flags (including open_how), mode, return value, errno, creation evidence', 'Conditional: read-only opens are level 0; writable access alone is not modification. O_CREAT alone does not prove creation. Confirmed new file is level 1; truncation of an existing file is level 2. Otherwise keep impact unresolved.'),
('openat', 'Opens a pathname relative to a directory descriptor and may create or truncate a file.', 'open', NULL, 'open_effect', 'path, dirfd/base path, flags (including open_how), mode, return value, errno, creation evidence', 'Conditional: read-only opens are level 0; writable access alone is not modification. O_CREAT alone does not prove creation. Confirmed new file is level 1; truncation of an existing file is level 2. Otherwise keep impact unresolved.'),
('openat2', 'Opens a pathname using structured access flags and path-resolution constraints.', 'open', NULL, 'open_effect', 'path, dirfd/base path, flags (including open_how), mode, return value, errno, creation evidence', 'Conditional: read-only opens are level 0; writable access alone is not modification. O_CREAT alone does not prove creation. Confirmed new file is level 1; truncation of an existing file is level 2. Otherwise keep impact unresolved.'),
('creat', 'Opens a file for writing with creation and truncation semantics.', 'open', NULL, 'open_effect', 'path, dirfd/base path, flags (including open_how), mode, return value, errno, creation evidence', 'Conditional: read-only opens are level 0; writable access alone is not modification. O_CREAT alone does not prove creation. Confirmed new file is level 1; truncation of an existing file is level 2. Otherwise keep impact unresolved.'),
('write', 'Writes bytes to a descriptor at its current offset.', 'write', 2, 'file_write', 'fd, target identity/type, requested bytes, returned bytes, errno, explicit offset and flags when applicable', 'Level 2 applies to file targets, not pipes, sockets or devices. Positive returned bytes establish bytes written, not that contents differ; zero bytes do not establish a modification. Do not capture buffer contents.'),
('writev', 'Writes bytes from multiple buffers to a descriptor.', 'write', 2, 'file_write', 'fd, target identity/type, requested bytes, returned bytes, errno, explicit offset and flags when applicable', 'Level 2 applies to file targets, not pipes, sockets or devices. Positive returned bytes establish bytes written, not that contents differ; zero bytes do not establish a modification. Do not capture buffer contents.'),
('pwrite64', 'Writes bytes to a descriptor using an explicit offset.', 'write', 2, 'file_write', 'fd, target identity/type, requested bytes, returned bytes, errno, explicit offset and flags when applicable', 'Level 2 applies to file targets, not pipes, sockets or devices. Positive returned bytes establish bytes written, not that contents differ; zero bytes do not establish a modification. Do not capture buffer contents.'),
('pwritev', 'Writes bytes from multiple buffers using an explicit offset.', 'write', 2, 'file_write', 'fd, target identity/type, requested bytes, returned bytes, errno, explicit offset and flags when applicable', 'Level 2 applies to file targets, not pipes, sockets or devices. Positive returned bytes establish bytes written, not that contents differ; zero bytes do not establish a modification. Do not capture buffer contents.'),
('pwritev2', 'Writes bytes from multiple buffers with offset and per-operation flags.', 'write', 2, 'file_write', 'fd, target identity/type, requested bytes, returned bytes, errno, explicit offset and flags when applicable', 'Level 2 applies to file targets, not pipes, sockets or devices. Positive returned bytes establish bytes written, not that contents differ; zero bytes do not establish a modification. Do not capture buffer contents.'),
('unlink', 'Removes a non-directory filesystem entry.', 'delete', 3, 'remove_entry', 'path, dirfd/base path where applicable, flags, return value, errno', 'Level 3 describes the requested operation. Only success confirms removal of an entry; open descriptors or other hard links may retain the data.'),
('unlinkat', 'Removes a filesystem entry relative to a directory descriptor, including directories with AT_REMOVEDIR.', 'delete', 3, 'remove_entry', 'path, dirfd/base path where applicable, flags, return value, errno', 'Level 3 describes the requested operation. Only success confirms removal of an entry; open descriptors or other hard links may retain the data.'),
('rmdir', 'Removes an empty directory.', 'delete', 3, 'remove_entry', 'path, dirfd/base path where applicable, flags, return value, errno', 'Level 3 describes the requested operation. Only success confirms removal of an entry; open descriptors or other hard links may retain the data.'),
('rename', 'Moves a filesystem entry and may replace an existing destination.', 'rename', NULL, 'rename_effect', 'source and destination paths/base descriptors, flags, return value, errno, destination replacement evidence', 'Confirmed move without replacement is level 2; confirmed destination replacement is level 3. Unknown replacement stays unresolved. RENAME_EXCHANGE exchanges entries (level 2); RENAME_WHITEOUT needs explicit interpretation. Successful same-object rename may be a no-op.'),
('renameat', 'Moves a filesystem entry using directory-relative source and destination paths.', 'rename', NULL, 'rename_effect', 'source and destination paths/base descriptors, flags, return value, errno, destination replacement evidence', 'Confirmed move without replacement is level 2; confirmed destination replacement is level 3. Unknown replacement stays unresolved. RENAME_EXCHANGE exchanges entries (level 2); RENAME_WHITEOUT needs explicit interpretation. Successful same-object rename may be a no-op.'),
('renameat2', 'Moves or exchanges filesystem entries with flag-controlled replacement behavior.', 'rename', NULL, 'rename_effect', 'source and destination paths/base descriptors, flags, return value, errno, destination replacement evidence', 'Confirmed move without replacement is level 2; confirmed destination replacement is level 3. Unknown replacement stays unresolved. RENAME_EXCHANGE exchanges entries (level 2); RENAME_WHITEOUT needs explicit interpretation. Successful same-object rename may be a no-op.'),
('truncate', 'Sets the length of a file identified by pathname.', 'resize', 2, 'file_resize', 'path or fd target identity/type, requested length, return value, errno, prior length when known', 'Success confirms the length-setting operation, not necessarily a length change; compare prior size only when reliable.'),
('ftruncate', 'Sets the length of a file identified by descriptor.', 'resize', 2, 'file_resize', 'path or fd target identity/type, requested length, return value, errno, prior length when known', 'Success confirms the length-setting operation, not necessarily a length change; compare prior size only when reliable.'),
('mkdir', 'Creates a directory with the requested permissions subject to the process umask.', 'create_directory', 1, 'directory_create', 'path, dirfd/base path where applicable, mode, return value, errno', 'Only success confirms directory creation. Record requested mode, not an assumed effective mode.'),
('mkdirat', 'Creates a directory relative to a directory descriptor.', 'create_directory', 1, 'directory_create', 'path, dirfd/base path where applicable, mode, return value, errno', 'Only success confirms directory creation. Record requested mode, not an assumed effective mode.'),
('read', 'Reads bytes from a descriptor.', 'read', 0, 'file_read', 'fd, target identity/type, requested bytes, returned bytes, errno, explicit offset and flags when applicable', 'Level 0 describes observation, not safety; secret reads can be sensitive and reads can update atime. Zero returned bytes do not prove content was read. Exclude non-file targets from filesystem classification.'),
('readv', 'Reads bytes from a descriptor into multiple buffers.', 'read', 0, 'file_read', 'fd, target identity/type, requested bytes, returned bytes, errno, explicit offset and flags when applicable', 'Level 0 describes observation, not safety; secret reads can be sensitive and reads can update atime. Zero returned bytes do not prove content was read. Exclude non-file targets from filesystem classification.'),
('pread64', 'Reads bytes from a descriptor using an explicit offset.', 'read', 0, 'file_read', 'fd, target identity/type, requested bytes, returned bytes, errno, explicit offset and flags when applicable', 'Level 0 describes observation, not safety; secret reads can be sensitive and reads can update atime. Zero returned bytes do not prove content was read. Exclude non-file targets from filesystem classification.'),
('preadv', 'Reads bytes into multiple buffers using an explicit offset.', 'read', 0, 'file_read', 'fd, target identity/type, requested bytes, returned bytes, errno, explicit offset and flags when applicable', 'Level 0 describes observation, not safety; secret reads can be sensitive and reads can update atime. Zero returned bytes do not prove content was read. Exclude non-file targets from filesystem classification.'),
('preadv2', 'Reads bytes into multiple buffers with offset and per-operation flags.', 'read', 0, 'file_read', 'fd, target identity/type, requested bytes, returned bytes, errno, explicit offset and flags when applicable', 'Level 0 describes observation, not safety; secret reads can be sensitive and reads can update atime. Zero returned bytes do not prove content was read. Exclude non-file targets from filesystem classification.'),
('stat', 'Retrieves file metadata by pathname while following symbolic links.', 'inspect', 0, 'inspect', 'path or fd identity, flags where applicable, return value, errno', 'Level 0 describes inspection, not harmlessness. Access checks do not establish a later read; metadata lookup does not prove file contents were accessed.'),
('lstat', 'Retrieves metadata for a pathname without following its final symbolic link.', 'inspect', 0, 'inspect', 'path or fd identity, flags where applicable, return value, errno', 'Level 0 describes inspection, not harmlessness. Access checks do not establish a later read; metadata lookup does not prove file contents were accessed.'),
('fstat', 'Retrieves metadata for a descriptor.', 'inspect', 0, 'inspect', 'path or fd identity, flags where applicable, return value, errno', 'Level 0 describes inspection, not harmlessness. Access checks do not establish a later read; metadata lookup does not prove file contents were accessed.'),
('newfstatat', 'Retrieves directory-relative file metadata with flag-controlled link handling.', 'inspect', 0, 'inspect', 'path or fd identity, flags where applicable, return value, errno', 'Level 0 describes inspection, not harmlessness. Access checks do not establish a later read; metadata lookup does not prove file contents were accessed.'),
('statx', 'Retrieves extended file metadata with a requested field mask.', 'inspect', 0, 'inspect', 'path or fd identity, flags where applicable, return value, errno', 'Level 0 describes inspection, not harmlessness. Access checks do not establish a later read; metadata lookup does not prove file contents were accessed.'),
('access', 'Checks accessibility of a pathname using the calling process credentials defined by access semantics.', 'inspect', 0, 'inspect', 'path or fd identity, flags where applicable, return value, errno', 'Level 0 describes inspection, not harmlessness. Access checks do not establish a later read; metadata lookup does not prove file contents were accessed.'),
('faccessat', 'Checks accessibility of a directory-relative pathname.', 'inspect', 0, 'inspect', 'path or fd identity, flags where applicable, return value, errno', 'Level 0 describes inspection, not harmlessness. Access checks do not establish a later read; metadata lookup does not prove file contents were accessed.'),
('faccessat2', 'Checks accessibility of a directory-relative pathname with explicit flags.', 'inspect', 0, 'inspect', 'path or fd identity, flags where applicable, return value, errno', 'Level 0 describes inspection, not harmlessness. Access checks do not establish a later read; metadata lookup does not prove file contents were accessed.'),
('readlink', 'Reads the stored target text of a symbolic link.', 'inspect', 0, 'inspect', 'path or fd identity, flags where applicable, return value, errno', 'Level 0 describes inspection, not harmlessness. Access checks do not establish a later read; metadata lookup does not prove file contents were accessed.'),
('readlinkat', 'Reads symbolic-link target text relative to a directory descriptor.', 'inspect', 0, 'inspect', 'path or fd identity, flags where applicable, return value, errno', 'Level 0 describes inspection, not harmlessness. Access checks do not establish a later read; metadata lookup does not prove file contents were accessed.'),
('getdents', 'Reads directory entries from a descriptor.', 'inspect', 0, 'inspect', 'path or fd identity, flags where applicable, return value, errno', 'Level 0 describes inspection, not harmlessness. Access checks do not establish a later read; metadata lookup does not prove file contents were accessed.'),
('getdents64', 'Reads directory entries using the 64-bit directory-entry format.', 'inspect', 0, 'inspect', 'path or fd identity, flags where applicable, return value, errno', 'Level 0 describes inspection, not harmlessness. Access checks do not establish a later read; metadata lookup does not prove file contents were accessed.'),
('getxattr', 'Reads an extended attribute associated with a pathname.', 'inspect', 0, 'inspect', 'path or fd identity, flags where applicable, return value, errno', 'Level 0 describes inspection, not harmlessness. Access checks do not establish a later read; metadata lookup does not prove file contents were accessed.'),
('lgetxattr', 'Reads an extended attribute without following the final symbolic link.', 'inspect', 0, 'inspect', 'path or fd identity, flags where applicable, return value, errno', 'Level 0 describes inspection, not harmlessness. Access checks do not establish a later read; metadata lookup does not prove file contents were accessed.'),
('fgetxattr', 'Reads an extended attribute from a descriptor.', 'inspect', 0, 'inspect', 'path or fd identity, flags where applicable, return value, errno', 'Level 0 describes inspection, not harmlessness. Access checks do not establish a later read; metadata lookup does not prove file contents were accessed.'),
('listxattr', 'Lists extended-attribute names associated with a pathname.', 'inspect', 0, 'inspect', 'path or fd identity, flags where applicable, return value, errno', 'Level 0 describes inspection, not harmlessness. Access checks do not establish a later read; metadata lookup does not prove file contents were accessed.'),
('llistxattr', 'Lists extended-attribute names without following the final symbolic link.', 'inspect', 0, 'inspect', 'path or fd identity, flags where applicable, return value, errno', 'Level 0 describes inspection, not harmlessness. Access checks do not establish a later read; metadata lookup does not prove file contents were accessed.'),
('flistxattr', 'Lists extended-attribute names associated with a descriptor.', 'inspect', 0, 'inspect', 'path or fd identity, flags where applicable, return value, errno', 'Level 0 describes inspection, not harmlessness. Access checks do not establish a later read; metadata lookup does not prove file contents were accessed.'),
('chmod', 'Changes permission bits for a pathname.', 'metadata_change', 2, 'metadata_change', 'path or fd identity, requested metadata/attribute name, flags, return value, errno', 'Level 2 describes a metadata operation. Success alone does not establish that values changed. Record attribute names but not potentially sensitive attribute values.'),
('fchmod', 'Changes permission bits for a descriptor.', 'metadata_change', 2, 'metadata_change', 'path or fd identity, requested metadata/attribute name, flags, return value, errno', 'Level 2 describes a metadata operation. Success alone does not establish that values changed. Record attribute names but not potentially sensitive attribute values.'),
('fchmodat', 'Changes permission bits for a directory-relative pathname.', 'metadata_change', 2, 'metadata_change', 'path or fd identity, requested metadata/attribute name, flags, return value, errno', 'Level 2 describes a metadata operation. Success alone does not establish that values changed. Record attribute names but not potentially sensitive attribute values.'),
('fchmodat2', 'Changes permission bits for a directory-relative pathname with explicit flags.', 'metadata_change', 2, 'metadata_change', 'path or fd identity, requested metadata/attribute name, flags, return value, errno', 'Level 2 describes a metadata operation. Success alone does not establish that values changed. Record attribute names but not potentially sensitive attribute values.'),
('chown', 'Changes ownership of a pathname while following symbolic links.', 'metadata_change', 2, 'metadata_change', 'path or fd identity, requested metadata/attribute name, flags, return value, errno', 'Level 2 describes a metadata operation. Success alone does not establish that values changed. Record attribute names but not potentially sensitive attribute values.'),
('lchown', 'Changes ownership without following the final symbolic link.', 'metadata_change', 2, 'metadata_change', 'path or fd identity, requested metadata/attribute name, flags, return value, errno', 'Level 2 describes a metadata operation. Success alone does not establish that values changed. Record attribute names but not potentially sensitive attribute values.'),
('fchown', 'Changes ownership of an object referenced by a descriptor.', 'metadata_change', 2, 'metadata_change', 'path or fd identity, requested metadata/attribute name, flags, return value, errno', 'Level 2 describes a metadata operation. Success alone does not establish that values changed. Record attribute names but not potentially sensitive attribute values.'),
('fchownat', 'Changes ownership of a directory-relative pathname with explicit flags.', 'metadata_change', 2, 'metadata_change', 'path or fd identity, requested metadata/attribute name, flags, return value, errno', 'Level 2 describes a metadata operation. Success alone does not establish that values changed. Record attribute names but not potentially sensitive attribute values.'),
('setxattr', 'Sets an extended attribute associated with a pathname.', 'metadata_change', 2, 'metadata_change', 'path or fd identity, requested metadata/attribute name, flags, return value, errno', 'Level 2 describes a metadata operation. Success alone does not establish that values changed. Record attribute names but not potentially sensitive attribute values.'),
('lsetxattr', 'Sets an extended attribute without following the final symbolic link.', 'metadata_change', 2, 'metadata_change', 'path or fd identity, requested metadata/attribute name, flags, return value, errno', 'Level 2 describes a metadata operation. Success alone does not establish that values changed. Record attribute names but not potentially sensitive attribute values.'),
('fsetxattr', 'Sets an extended attribute associated with a descriptor.', 'metadata_change', 2, 'metadata_change', 'path or fd identity, requested metadata/attribute name, flags, return value, errno', 'Level 2 describes a metadata operation. Success alone does not establish that values changed. Record attribute names but not potentially sensitive attribute values.'),
('removexattr', 'Removes an extended attribute associated with a pathname.', 'metadata_change', 2, 'metadata_change', 'path or fd identity, requested metadata/attribute name, flags, return value, errno', 'Level 2 describes a metadata operation. Success alone does not establish that values changed. Record attribute names but not potentially sensitive attribute values.'),
('lremovexattr', 'Removes an extended attribute without following the final symbolic link.', 'metadata_change', 2, 'metadata_change', 'path or fd identity, requested metadata/attribute name, flags, return value, errno', 'Level 2 describes a metadata operation. Success alone does not establish that values changed. Record attribute names but not potentially sensitive attribute values.'),
('fremovexattr', 'Removes an extended attribute associated with a descriptor.', 'metadata_change', 2, 'metadata_change', 'path or fd identity, requested metadata/attribute name, flags, return value, errno', 'Level 2 describes a metadata operation. Success alone does not establish that values changed. Record attribute names but not potentially sensitive attribute values.'),
('utime', 'Updates file access and modification timestamps with second precision.', 'metadata_change', 2, 'metadata_change', 'path or fd identity, requested metadata/attribute name, flags, return value, errno', 'Level 2 describes a metadata operation. Success alone does not establish that values changed. Record attribute names but not potentially sensitive attribute values.'),
('utimes', 'Updates file access and modification timestamps with microsecond precision.', 'metadata_change', 2, 'metadata_change', 'path or fd identity, requested metadata/attribute name, flags, return value, errno', 'Level 2 describes a metadata operation. Success alone does not establish that values changed. Record attribute names but not potentially sensitive attribute values.'),
('futimesat', 'Updates timestamps for a directory-relative pathname.', 'metadata_change', 2, 'metadata_change', 'path or fd identity, requested metadata/attribute name, flags, return value, errno', 'Level 2 describes a metadata operation. Success alone does not establish that values changed. Record attribute names but not potentially sensitive attribute values.'),
('utimensat', 'Updates file timestamps with nanosecond precision and explicit flags.', 'metadata_change', 2, 'metadata_change', 'path or fd identity, requested metadata/attribute name, flags, return value, errno', 'Level 2 describes a metadata operation. Success alone does not establish that values changed. Record attribute names but not potentially sensitive attribute values.'),
('link', 'Creates an additional hard link to an existing file.', 'link', 1, 'link_create', 'source/target text and new path, directory bases, flags, return value, errno', 'Level 1 describes adding an entry, not duplicating file contents or guaranteeing a harmless target.'),
('linkat', 'Creates a hard link using directory-relative paths and flags.', 'link', 1, 'link_create', 'source/target text and new path, directory bases, flags, return value, errno', 'Level 1 describes adding an entry, not duplicating file contents or guaranteeing a harmless target.'),
('symlink', 'Creates a symbolic link containing the supplied target text.', 'link', 1, 'link_create', 'source/target text and new path, directory bases, flags, return value, errno', 'Level 1 describes adding an entry, not duplicating file contents or guaranteeing a harmless target.'),
('symlinkat', 'Creates a symbolic link relative to a directory descriptor.', 'link', 1, 'link_create', 'source/target text and new path, directory bases, flags, return value, errno', 'Level 1 describes adding an entry, not duplicating file contents or guaranteeing a harmless target.'),
('copy_file_range', 'Copies a range of data between file descriptors without a userspace buffer.', 'copy', NULL, 'copy_effect', 'source/destination fd identities and types, offsets, requested and returned bytes, flags, errno, destination creation evidence', 'Require a file destination before assigning filesystem impact. Positive transferred bytes to an existing file are level 2; confirmed creation is a separate level 1 event. Pipe/socket destinations are not file edits. Do not infer secret exfiltration.'),
('sendfile', 'Transfers data from an input file descriptor to an output descriptor.', 'copy', NULL, 'copy_effect', 'source/destination fd identities and types, offsets, requested and returned bytes, flags, errno, destination creation evidence', 'Require a file destination before assigning filesystem impact. Positive transferred bytes to an existing file are level 2; confirmed creation is a separate level 1 event. Pipe/socket destinations are not file edits. Do not infer secret exfiltration.'),
('splice', 'Transfers data between descriptors with at least one pipe endpoint.', 'copy', NULL, 'copy_effect', 'source/destination fd identities and types, offsets, requested and returned bytes, flags, errno, destination creation evidence', 'Require a file destination before assigning filesystem impact. Positive transferred bytes to an existing file are level 2; confirmed creation is a separate level 1 event. Pipe/socket destinations are not file edits. Do not infer secret exfiltration.'),
('fallocate', 'Allocates or changes file ranges according to mode flags.', 'resize', NULL, 'allocation_effect', 'fd target identity/type, mode flags, offset, length, return value, errno', 'Decoded successful allocation/range changes on files are level 2; punch-hole, zero-range, collapse-range and insert-range may alter data. Allocation alone does not prove changed contents.'),
('ioctl', 'Performs a command-specific operation on a descriptor, which may affect file data or metadata.', 'metadata_change', NULL, 'ioctl_effect', 'fd target identity/type, decoded ioctl command and relevant arguments, return value, errno', 'No generic impact. Decode supported commands: file clone/range clone to an existing destination is level 2, file attribute changes are level 2, inspection is level 0. Unknown commands remain unclassified.'),
('mmap', 'Maps a file or anonymous memory into the process address space.', 'mapping', NULL, 'mapping_effect', 'file identity and fd where available, address/range, protections, mapping flags, tracked mapping identity, return value, errno', 'A readable file mapping indicates possible access, not confirmed reads; a shared writable mapping indicates possible modification, not actual writes. Mapping/protection/sync/unmap calls alone do not confirm changed bytes; leave impact unresolved without additional evidence.'),
('mprotect', 'Changes access protections for a mapped memory range.', 'mapping', NULL, 'mapping_effect', 'file identity and fd where available, address/range, protections, mapping flags, tracked mapping identity, return value, errno', 'A readable file mapping indicates possible access, not confirmed reads; a shared writable mapping indicates possible modification, not actual writes. Mapping/protection/sync/unmap calls alone do not confirm changed bytes; leave impact unresolved without additional evidence.'),
('msync', 'Requests synchronization of a mapped file range with its backing storage.', 'mapping', NULL, 'mapping_effect', 'file identity and fd where available, address/range, protections, mapping flags, tracked mapping identity, return value, errno', 'A readable file mapping indicates possible access, not confirmed reads; a shared writable mapping indicates possible modification, not actual writes. Mapping/protection/sync/unmap calls alone do not confirm changed bytes; leave impact unresolved without additional evidence.'),
('munmap', 'Removes mappings from a process address range.', 'mapping', NULL, 'mapping_effect', 'file identity and fd where available, address/range, protections, mapping flags, tracked mapping identity, return value, errno', 'A readable file mapping indicates possible access, not confirmed reads; a shared writable mapping indicates possible modification, not actual writes. Mapping/protection/sync/unmap calls alone do not confirm changed bytes; leave impact unresolved without additional evidence.'),
('close', 'Closes a file descriptor.', 'descriptor_bookkeeping', NULL, 'bookkeeping', 'process identity, relevant descriptors/paths, command or flags, return value, errno', 'No direct filesystem impact level. Retain as context; closing or syncing can flush earlier writes but is not a new confirmed content edit. fcntl requires command decoding and is not automatically a file mutation.'),
('close_range', 'Closes a range of descriptors or marks them close-on-exec according to flags.', 'descriptor_bookkeeping', NULL, 'bookkeeping', 'process identity, relevant descriptors/paths, command or flags, return value, errno', 'No direct filesystem impact level. Retain as context; closing or syncing can flush earlier writes but is not a new confirmed content edit. fcntl requires command decoding and is not automatically a file mutation.'),
('dup', 'Duplicates a descriptor into the lowest available descriptor number.', 'descriptor_bookkeeping', NULL, 'bookkeeping', 'process identity, relevant descriptors/paths, command or flags, return value, errno', 'No direct filesystem impact level. Retain as context; closing or syncing can flush earlier writes but is not a new confirmed content edit. fcntl requires command decoding and is not automatically a file mutation.'),
('dup2', 'Duplicates a descriptor into a specified descriptor number.', 'descriptor_bookkeeping', NULL, 'bookkeeping', 'process identity, relevant descriptors/paths, command or flags, return value, errno', 'No direct filesystem impact level. Retain as context; closing or syncing can flush earlier writes but is not a new confirmed content edit. fcntl requires command decoding and is not automatically a file mutation.'),
('dup3', 'Duplicates a descriptor into a specified number with explicit flags.', 'descriptor_bookkeeping', NULL, 'bookkeeping', 'process identity, relevant descriptors/paths, command or flags, return value, errno', 'No direct filesystem impact level. Retain as context; closing or syncing can flush earlier writes but is not a new confirmed content edit. fcntl requires command decoding and is not automatically a file mutation.'),
('fcntl', 'Performs descriptor control operations such as duplication or flag changes.', 'descriptor_bookkeeping', NULL, 'bookkeeping', 'process identity, relevant descriptors/paths, command or flags, return value, errno', 'No direct filesystem impact level. Retain as context; closing or syncing can flush earlier writes but is not a new confirmed content edit. fcntl requires command decoding and is not automatically a file mutation.'),
('lseek', 'Changes the file offset associated with a descriptor.', 'descriptor_bookkeeping', NULL, 'bookkeeping', 'process identity, relevant descriptors/paths, command or flags, return value, errno', 'No direct filesystem impact level. Retain as context; closing or syncing can flush earlier writes but is not a new confirmed content edit. fcntl requires command decoding and is not automatically a file mutation.'),
('chdir', 'Changes the working directory used to interpret relative paths.', 'descriptor_bookkeeping', NULL, 'bookkeeping', 'process identity, relevant descriptors/paths, command or flags, return value, errno', 'No direct filesystem impact level. Retain as context; closing or syncing can flush earlier writes but is not a new confirmed content edit. fcntl requires command decoding and is not automatically a file mutation.'),
('fchdir', 'Changes the working directory using a directory descriptor.', 'descriptor_bookkeeping', NULL, 'bookkeeping', 'process identity, relevant descriptors/paths, command or flags, return value, errno', 'No direct filesystem impact level. Retain as context; closing or syncing can flush earlier writes but is not a new confirmed content edit. fcntl requires command decoding and is not automatically a file mutation.'),
('fsync', 'Requests synchronization of file data and metadata to storage.', 'descriptor_bookkeeping', NULL, 'bookkeeping', 'process identity, relevant descriptors/paths, command or flags, return value, errno', 'No direct filesystem impact level. Retain as context; closing or syncing can flush earlier writes but is not a new confirmed content edit. fcntl requires command decoding and is not automatically a file mutation.'),
('fdatasync', 'Requests synchronization of file data and necessary metadata to storage.', 'descriptor_bookkeeping', NULL, 'bookkeeping', 'process identity, relevant descriptors/paths, command or flags, return value, errno', 'No direct filesystem impact level. Retain as context; closing or syncing can flush earlier writes but is not a new confirmed content edit. fcntl requires command decoding and is not automatically a file mutation.')
ON CONFLICT(syscall_name) DO UPDATE SET
    description=excluded.description,
    category_id=excluded.category_id,
    default_impact_level=excluded.default_impact_level,
    classification_rule=excluded.classification_rule,
    required_evidence=excluded.required_evidence,
    interpretation_notes=excluded.interpretation_notes,
    catalog_version=excluded.catalog_version;

CREATE VIEW IF NOT EXISTS syscall_catalog_readable AS
SELECT s.syscall_name, s.description, s.category_id, c.label AS category,
       s.default_impact_level, i.label AS impact_label,
       s.classification_rule, s.required_evidence, s.interpretation_notes,
       s.catalog_version
FROM syscall_catalog AS s
JOIN syscall_categories AS c ON c.category_id = s.category_id
LEFT JOIN syscall_impact_levels AS i ON i.level = s.default_impact_level;

COMMIT;

-- Example: SELECT syscall_name, category, default_impact_level
--          FROM syscall_catalog_readable WHERE syscall_name = 'unlinkat';
-- Result: unlinkat | Delete | 3

